name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'  # Фиксированная стабильная версия

      - name: Install pnpm
        uses: pnpm/action-setup@v4  # Обновлено с v2 на v4
        with:
          version: 9  # Обновлено с 8 на 9

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Обновлено с v3 на v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out